### ISSUE TITLE
FY23 DRAFT Template QC Checklist

### ISSUE THREAD

**Issue by nmcdavid** [USAID-OHA-SI/Interesting#15]
Below are a list of checks I would like you to review. Please feel free to expand on this list

**Meta tab** 
- [ ] Sheet is protected
- [ ] Long and Semi-wide allow for use of pivot table
- [ ] Reporting period cell C3 drop down is "FY23"
- [ ] OU cell B3 drop down is functional
- [ ] Template Version = 2.02
- [ ] Columns are hidden
- [ ] Gridlines removed
- [ ] Headers removed
- [ ] Are cells B3:C3 unlocked for editing

**Data reporting tabs**
- [ ] Sheet is protected
- [ ] Tab name end in "CIRG"
- [ ] Hidden columns 
- [ ] Reporting period column A drop down is "FY23"
- [ ] OU column F drop down is functional
- [ ] Borders formatted to show sections
- [ ] User can insert row
- [ ] User can resize column
- [ ] Are all cells below row 3 unlocked
- [ ] Notes are useful and informative

**Long template**
- [ ] Indicator dependent drop-down selection for Age, Sex, Other disagg, Population, and Numerator/denominator work
- [ ] Do the drop down selections align with indicator reference guide
- [ ] Semi-wide template
- [ ] Do the drop down selections align with indicator reference guide
- [ ] Are all indicators present

**Wide**
- [ ] Tab names are clear
- [ ] All possible disaggregation combos are present
- [ ] Disaggregation combos are in the best order (ages bands are in order)

**Comment by BBetz907** [comment]
Great work on these Nashiva! I worked through the checklist on the long template, semi-wide, PrEP. and KP. Only issue I found was that the dropdown menu for reporting period on the meta tab and cirg tab for KP still read FY22. I then checked every other template and found the issue did not occur elsewhere. I suspect you simply left the old CIRG period there to make sure I'm doing my job ;)

**Comment by nmcdavid** [comment]
> 

Ha- thanks for catching that. And to save face I'll go with your explanation. Makes me sound diabolical :-)

I'll double check all reporting period dropdowns to make sure they read FY23
